
# Avec Oracle
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
#spring.datasource.username=gabesfaculty
#spring.datasource.password=BJ240005
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


spring.application.name=timetable
server.port=8082


# ==================================================
# DATABASE
# ==================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/gabesfaculty
spring.datasource.username=postgres
spring.datasource.password=prehisto
spring.datasource.driver-class-name=org.postgresql.Driver


# ==================================================
# JPA / HIBERNATE
# ==================================================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
# Ne pas afficher les requêtes SQL
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Désactiver les logs SQL Hibernate
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.orm.jdbc.extract=OFF


# ==================================================
# LOGGING
# ==================================================

logging.level.root=INFO

# Spring Security
logging.level.org.springframework.security=INFO

# JavaMail / SMTP
logging.level.org.springframework.mail=OFF
logging.level.org.eclipse.angus.mail=OFF
logging.level.jakarta.mail=OFF
logging.level.com.sun.mail=OFF


# ==================================================
# SPRING
# ==================================================

spring.main.allow-circular-references=true

spring.config.import=optional:file:.env


# ==================================================
# MAIL
# ==================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akabeb.com@gmail.com
spring.mail.password=qolp gydx loco rgfo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com



# ==================================================
# ENCODING
# ==================================================

server.tomcat.uri-encoding=UTF-8

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


# ==================================================
# THYMELEAF
# ==================================================

spring.thymeleaf.cache=true


# ==================================================
# SESSION
# ==================================================

# server.servlet.session.timeout=3m


