package com.belak.scheduletimetable.enumeration;

public enum Filiere {

    LCHI("LCH", "LICENCE EN CHIMIE"),
    LCHR("LCHR", "LICENCE EN CHIMIE R"),

    LPHY("LPH", "LICENCE EN PHYSIQUE"),
    LMAT("LMA", "LICENCE EN MATHEMATIQUES"),
    LSV("LSV", "LICENCE EN SCIENCE DE LA VIE"),
    LST("LST", "LICENCE EN SCIENCE DE LA TERRE"),
    LGEOR("LGEOR", "LICENCE EN SCIENCE DE LA TERRE"),
    LSVT("LSVT", "LICENCE EN SCIENCE DE LA VIE ET DE LA TERRE"),
    LSI("LGLSI", "LICENCE EN SCIENCES INFORMATIQUES"),
    LISI("LIRS", "LICENCE EN INGENIERIE DES SYSTEMES INFORMATIQUES"),
    LMPI("LMPI", "LICENCE EN MESURES PHYSIQUES ET INSTRUMENTATIONS"),
    LBIO("LBT", "LICENCE EN BIOTECHNOLOGIE"),
    LEEA("LEEA", "LICENCE EN ELECTRONIQUE ELECTROTECHNIQUE ET AUTOMATISME"),

    MR_MATH("MRMA", "MASTER DE RECHERCHE EN MATHEMATIQUES"),
    MR_PVMA("MRPVM", "MASTER DE RECHERCHE EN PATHOGENIE VIRULENCE DES MICROORGANISMES ET AGENTS"),
    MR_CME("MRCME", "MASTER DE RECHERCHE EN CHIMIE MATERIAUX ET ENVIRONNEMENT"),
    MR_PMN("MR-PMN", "MASTER DE RECHERCHE EN PHYSIQUE DES MATERIAUX ET DES NANOMATERIAUX"),
    MR_PH("MRPH", "MASTER DE RECHERCHE EN PHYSIQUE DES MATERIAUX ET DES NANOMATERIAUX"),
    MP_SSRI("MPSSIR", "MASTER PROFESSIONNEL EN SECURITES DES SYSTEMES ET DES RESEAUX INFORMATIQUES"),
    MP_VGM("MPVG", "MASTER PROFESSIONNEL EN VALORISATION DES GEO-MATERIAUX"),
    MR_MGB("MRMGB", "MASTER DE RECHERCHE EN MICROBIOLOGIE, GENETIQUE ET BIORESSOURCES"),
    MR_GBS("MRGBS", "MASTER DE RECHERCHE EN GEOLOGIE DES BASSINS SEDIMENTAIRES"),
    MR_BOPE("MRBOPE", "MASTER DE RECHERCHE EN BIOLOGIE DES ORGANISMES, DES POPULATIONS ET ENVIRONNEMENT"),
    MR_BOPEA("MRBOPEA", "MASTER DE RECHERCHE EN BIOLOGIE DES ORGANISMES, DES POPULATIONS ET ENVIRONNEMENT"),
    MR_IR("MRIR", "MASTER DE RECHERCHE EN INFORMATIQUE ET RESEAUX");

    private final String code;
    private final String libelle;

    Filiere(String code, String libelle) {
        this.code = code;
        this.libelle = libelle;
    }

    public String getCode() {
        return code;
    }

    public String getLibelle() {
        return libelle;
    }

    public static Filiere fromCode(String code) {
        for (Filiere d : Filiere.values()) {
            if (d.code.equalsIgnoreCase(code)) {
                return d;
            }
        }
        throw new IllegalArgumentException("Code inconnu pour Diplome : " + code);
    }
}

